/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@ApiModel(description = "")

public class CatalogQueryItemsForItemOptions {
  @JsonProperty("item_option_ids")
  private List<String> itemOptionIds = new ArrayList<String>();

  public CatalogQueryItemsForItemOptions itemOptionIds(List<String> itemOptionIds) {
    this.itemOptionIds = itemOptionIds;
    return this;
  }

  public CatalogQueryItemsForItemOptions addItemOptionIdsItem(String itemOptionIdsItem) {
    this.itemOptionIds.add(itemOptionIdsItem);
    return this;
  }

   /**
   * A set of [CatalogItemOption](#type-catalogitemoption) IDs to be used to find associated [CatalogItem](#type-catalogitem)s. All Items that contain all of the given Item Options (in any order) will be returned.
   * @return itemOptionIds
  **/
  @ApiModelProperty(value = "A set of [CatalogItemOption](#type-catalogitemoption) IDs to be used to find associated [CatalogItem](#type-catalogitem)s. All Items that contain all of the given Item Options (in any order) will be returned.")
  public List<String> getItemOptionIds() {
    return itemOptionIds;
  }

  public void setItemOptionIds(List<String> itemOptionIds) {
    this.itemOptionIds = itemOptionIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogQueryItemsForItemOptions catalogQueryItemsForItemOptions = (CatalogQueryItemsForItemOptions) o;
    return Objects.equals(this.itemOptionIds, catalogQueryItemsForItemOptions.itemOptionIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemOptionIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogQueryItemsForItemOptions {\n");

    sb.append("    itemOptionIds: ").append(toIndentedString(itemOptionIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

