/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A request for a set of &#x60;WorkweekConfig&#x60; objects
 */
@ApiModel(description = "A request for a set of `WorkweekConfig` objects")

public class ListWorkweekConfigsRequest {
  @JsonProperty("limit")
  private Integer limit = null;

  @JsonProperty("cursor")
  private String cursor = null;

  public ListWorkweekConfigsRequest limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Maximum number of Workweek Configs to return per page.
   * @return limit
  **/
  @ApiModelProperty(value = "Maximum number of Workweek Configs to return per page.")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public ListWorkweekConfigsRequest cursor(String cursor) {
    this.cursor = cursor;
    return this;
  }

   /**
   * Pointer to the next page of Workweek Config results to fetch.
   * @return cursor
  **/
  @ApiModelProperty(value = "Pointer to the next page of Workweek Config results to fetch.")
  public String getCursor() {
    return cursor;
  }

  public void setCursor(String cursor) {
    this.cursor = cursor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWorkweekConfigsRequest listWorkweekConfigsRequest = (ListWorkweekConfigsRequest) o;
    return Objects.equals(this.limit, listWorkweekConfigsRequest.limit) &&
        Objects.equals(this.cursor, listWorkweekConfigsRequest.cursor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, cursor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWorkweekConfigsRequest {\n");

    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

