/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.squareup.connect.models.Error;
import com.squareup.connect.models.InventoryCount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@ApiModel(description = "")

public class RetrieveInventoryCountResponse {
  @JsonProperty("errors")
  private List<Error> errors = new ArrayList<Error>();

  @JsonProperty("counts")
  private List<InventoryCount> counts = new ArrayList<InventoryCount>();

  @JsonProperty("cursor")
  private String cursor = null;

  public RetrieveInventoryCountResponse errors(List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public RetrieveInventoryCountResponse addErrorsItem(Error errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Any errors that occurred during the request.
   * @return errors
  **/
  @ApiModelProperty(value = "Any errors that occurred during the request.")
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }

  public RetrieveInventoryCountResponse counts(List<InventoryCount> counts) {
    this.counts = counts;
    return this;
  }

  public RetrieveInventoryCountResponse addCountsItem(InventoryCount countsItem) {
    this.counts.add(countsItem);
    return this;
  }

   /**
   * The current calculated inventory counts for the requested object and locations.
   * @return counts
  **/
  @ApiModelProperty(value = "The current calculated inventory counts for the requested object and locations.")
  public List<InventoryCount> getCounts() {
    return counts;
  }

  public void setCounts(List<InventoryCount> counts) {
    this.counts = counts;
  }

  public RetrieveInventoryCountResponse cursor(String cursor) {
    this.cursor = cursor;
    return this;
  }

   /**
   * The pagination cursor to be used in a subsequent request. If unset, this is the final response.  See [Pagination](/basics/api101/pagination) for more information.
   * @return cursor
  **/
  @ApiModelProperty(value = "The pagination cursor to be used in a subsequent request. If unset, this is the final response.  See [Pagination](/basics/api101/pagination) for more information.")
  public String getCursor() {
    return cursor;
  }

  public void setCursor(String cursor) {
    this.cursor = cursor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveInventoryCountResponse retrieveInventoryCountResponse = (RetrieveInventoryCountResponse) o;
    return Objects.equals(this.errors, retrieveInventoryCountResponse.errors) &&
        Objects.equals(this.counts, retrieveInventoryCountResponse.counts) &&
        Objects.equals(this.cursor, retrieveInventoryCountResponse.cursor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, counts, cursor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveInventoryCountResponse {\n");

    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    counts: ").append(toIndentedString(counts)).append("\n");
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

