/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.squareup.connect.models.V1EmployeeRole;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 */
@ApiModel(description = "")

public class V1CreateEmployeeRoleRequest {
  @JsonProperty("employee_role")
  private V1EmployeeRole employeeRole = null;

  public V1CreateEmployeeRoleRequest employeeRole(V1EmployeeRole employeeRole) {
    this.employeeRole = employeeRole;
    return this;
  }

   /**
   * An EmployeeRole object with a name and permissions, and an optional owner flag.
   * @return employeeRole
  **/
  @ApiModelProperty(value = "An EmployeeRole object with a name and permissions, and an optional owner flag.")
  public V1EmployeeRole getEmployeeRole() {
    return employeeRole;
  }

  public void setEmployeeRole(V1EmployeeRole employeeRole) {
    this.employeeRole = employeeRole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CreateEmployeeRoleRequest v1CreateEmployeeRoleRequest = (V1CreateEmployeeRoleRequest) o;
    return Objects.equals(this.employeeRole, v1CreateEmployeeRoleRequest.employeeRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeRole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CreateEmployeeRoleRequest {\n");

    sb.append("    employeeRole: ").append(toIndentedString(employeeRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

