/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.api;

import com.squareup.connect.ApiException;
import com.squareup.connect.models.GetPaymentRefundResponse;
import com.squareup.connect.models.ListPaymentRefundsResponse;
import com.squareup.connect.models.RefundPaymentRequest;
import com.squareup.connect.models.RefundPaymentResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RefundsApi
 */
@Ignore
public class RefundsApiTest {

    private final RefundsApi api = new RefundsApi();


    /**
     * GetPaymentRefund
     *
     * Retrieves a specific &#x60;Refund&#x60; using the &#x60;refund_id&#x60;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentRefundTest() throws ApiException {
        String refundId = null;
        GetPaymentRefundResponse response = api.getPaymentRefund(refundId);

        // TODO: test validations
    }

    /**
     * ListPaymentRefunds
     *
     * Retrieves a list of refunds for the account making the request.  Max results per page: 100
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPaymentRefundsTest() throws ApiException {
        String beginTime = null;
        String endTime = null;
        String sortOrder = null;
        String cursor = null;
        String locationId = null;
        String status = null;
        String sourceType = null;
        ListPaymentRefundsResponse response = api.listPaymentRefunds(beginTime, endTime, sortOrder, cursor, locationId, status, sourceType);

        // TODO: test validations
    }

    /**
     * RefundPayment
     *
     * Refunds a payment. You can refund the entire payment amount or a  portion of it. For more information, see  [Payments and Refunds Overview](/payments-api/overview).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refundPaymentTest() throws ApiException {
        RefundPaymentRequest body = null;
        RefundPaymentResponse response = api.refundPayment(body);

        // TODO: test validations
    }

}
